#服务配置
server:
  port: 80
  max-http-header-size: 10240

#spring相关配置
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    date-format: com.bootdo.config.converter.JsonDateFormat

#mybaits相关配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml, classpath:/META-INF/modeler-mybatis-mappings/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
    enable-sql-runner: true
  configuration-properties:
    prefix:
    #如果数据库为postgresql，则需要配置为blobType: BINARY
    blobType: BLOB
    #如果数据库为oracle或mssql，则需要配置为boolValue: 1
    boolValue: true